###############################################################################
# Core plugins to load at startup
###############################################################################

plugins:
  - name: renderer_gl
    version: "0.0.1"
    version_policy: minimum
    optional: false

  - name: input
    version: "0.0.1"
    version_policy: minimum
    optional: false

  - name: menu
    version: "0.0.1"
    version_policy: minimum
    optional: false

  - name: python
    version: "0.0.1"
    version_policy: minimum
    optional: true

  - name: d_example
    version: "0.0.1"
    version_policy: minimum
    optional: false

###############################################################################
# Client settings
###############################################################################

client:
    hosts:
      - "localhost"
      - "game.pixelcloud.ch"

###############################################################################
# Server settings
###############################################################################

server:
    name: "Lightship Server"
    port: 9111
    ip_whitelist: false
    ip_ban_file: banned_ips.txt
    max_games: 5
    max_connections: 20


